version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173" # Frontend (Vite React App) exposed on port 5173
    depends_on:
      - backend

  backend:
    build:
      context: ./extension-service
    ports:
      - "4000:4000" # Backend exposed on port 4000
    environment:
      - MONGO_URI=mongodb://mongo:27017/extensionsdb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # MongoDB exposed on port 27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
