version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173" # Frontend (Vite React App) exposed on port 5173
    depends_on:
      - backend

  backend:
    build:
      context: ./extension-service
    ports:
      - "4000:4000" # Backend exposed on port 4000
    environment:
      # - MONGO_URI=mongodb+srv:/ABCD.mongodb.net/extensionsDB # Use your MongoDB Atlas URI

volumes:
  mongo_data:
